Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@kwedwick 
210726-wvu-net-ext
/
P2-Chris-Du-Keegan
Public
1
0
0
Code
Issues
Pull requests
1
Actions
Projects
Wiki
Security
Insights
Settings
P2-Chris-Du-Keegan/PostNApp/azure-pipelines.yml
@kwedwick
kwedwick Merge branch 'Develop'
…
Latest commit f4851c1 19 minutes ago
 History
 1 contributor
65 lines (55 sloc)  1.78 KB
  
trigger:
- Develop

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: './PostNApp/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  postNAppDirectory: './PostNApp'
  postNAppUIDirectory: './PostNApp-UI'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloudP2'
        organization: '210726-wvu-net-ext'
        scannerMode: 'MSBuild'
        projectKey: '210726-wvu-net-ext_P2-Chris-Du-Keegan'
        projectName: 'P2-Chris-Du-Keegan'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - script: dotnet test
        --configuration Release
        --collect:"XPlat Code Coverage"
        --results-directory $(Agent.TempDirectory)
        --
        DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      displayName: dotnet test
      workingDirectory: $(postNAppDirectory)

    - task: SonarCloudAnalyze@1
      displayName: 'Run SonarCloud analysis'

    - task: SonarCloudPublish@1
      displayName: 'Publish results on build summary'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
Loading complete